import React from "react";
import { Link } from "react-router-dom";

const Terms = () => {
  return (
    <div style={{ background: "#0c0c0e", minHeight: "100vh", color: "white", paddingTop: "80px", paddingBottom: "40px" }}>
      <div className="container" style={{ maxWidth: "800px" }}>
        <div className="glass-card p-5 rounded-4 border border-secondary border-opacity-20" style={{ background: "rgba(25, 25, 25, 0.45)", backdropFilter: "blur(12px)" }}>
          
          <h1 className="fw-bold text-warning mb-2">Terms & Conditions</h1>
          <p className="text-secondary mb-4 small">Last Updated: [Informational Placeholder]</p>
          
          <div className="text-light" style={{ lineHeight: "1.8", fontSize: "0.95rem" }}>
            <p>
              Welcome to TripShare! These Terms & Conditions govern your use of the TripShare platform.
              <br /><br />
              <strong className="text-warning">NOTE:</strong> This document is an informational placeholder pending professional legal review. 
            </p>

            <h4 className="text-warning mt-4 mb-3">1. Acceptance of Terms</h4>
            <p>
              By accessing or using TripShare, you agree to be bound by these placeholder terms. If you disagree with any part of the terms, you may not access the service.
            </p>

            <h4 className="text-warning mt-4 mb-3">2. User Accounts</h4>
            <p>
              You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.
            </p>

            <h4 className="text-warning mt-4 mb-3">3. AI Services & Disclaimers</h4>
            <p>
              TripShare AI is a generalized LLM (Large Language Model) travel assistant. Its recommendations, itineraries, and cost estimates are generated by artificial intelligence and are prone to hallucinations or outdated information. 
              <br /><br />
              <strong>TripShare AI is NOT a substitute for professional legal, medical, or guaranteed travel advice.</strong> You must independently verify visa requirements, safety conditions, and pricing.
            </p>

            <h4 className="text-warning mt-4 mb-3">4. Limitation of Liability</h4>
            <p>
              In no event shall TripShare, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>

          </div>

          <div className="mt-5 pt-4 border-top border-secondary border-opacity-20">
            <Link to="/" className="btn btn-outline-warning rounded-pill px-4">Return Home</Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
